myapp/__init__.py
import os 
from flask import Flask
from myapp.auth.auth import auth
from myapp.views.home import main
from myapp.views.posts import posts
from flask_login import LoginManager
from flask import send_from_directory
from myapp.model.db_extension import db
from myapp.model.ma_extension import ma
from myapp.model.model import User
from myapp.model.post_model import Posts


def create_app(test_config='config'):
    app = Flask(__name__, instance_relative_config=True)

    # app.config.from_object('config')
    if test_config is None:
        # load the instance config, if it exists, when not testing
        app.config.from_pyfile('config.py', silent=True)
    else:
        # load the test config if passed in
        app.config.from_object(test_config)

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    app.register_blueprint(main)
    # app.register_blueprint(api)
    app.register_blueprint(auth)
    app.register_blueprint(posts)

    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    db.init_app(app)
    ma.init_app(app)


    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(int(user_id))


    @app.route('/favicon.ico') 
    def favicon(): 
        return send_from_directory(os.path.join(app.root_path, 'static\\assets'), 'favicon.ico', mimetype='image/vnd.microsoft.icon')

    return app

myapp/views/home.py
from flask import Blueprint, render_template
from flask_login import login_required, current_user

main = Blueprint('main', __name__)

@main.route('/')
def home_page():
    return render_template('index.html')

@main.route('/profile')
@login_required
def get_profile():
    return render_template('profile.html', username=current_user.username)

myapp/views/posts.py
from flask.json import jsonify
from myapp.model.post_model import Posts, PostsSchema
from flask import Blueprint, render_template, url_for
from flask_login import login_required, current_user

posts = Blueprint('posts', __name__, url_prefix='/api')

@posts.route('/getposts', methods=['GET', 'POST'])
@login_required
def get_posts():
    all_posts = Posts.query.filter_by(user_id=current_user.id)
    if all_posts:
        user_posts = all_posts.all()
        post_schema = PostsSchema(many=True)
        output = post_schema.dump(user_posts)
        return render_template('posts.html', all_posts=output)

        # return jsonify(output)
    else:
        return render_template('posts.html', all_posts=[])

@posts.route('/createpost', methods=['POST'])
@login_required
def create_post():
    pass

@login_required
@posts.route('/updatepost',methods=['PUT'])
def update_post():
    pass

@login_required
@posts.route('/deletepost',methods=['DELETE'])
def delete_post():
    pass

myapp/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Flask Auth Example</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css" />
</head>

<body>
    <section class="hero is-primary is-fullheight">

        <div class="hero-head">
            <nav class="navbar">
                <div class="container">

                    <div id="navbarMenuHeroA" class="navbar-menu">
                        <div class="navbar-end">
                            <a href="{{ url_for('main.home_page') }}" class="navbar-item">
                                Home
                            </a>

                            
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('main.get_profile') }}" class="navbar-item">
                                Profile
                            </a>
                            {% endif %}

                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('posts.get_posts') }}" class="navbar-item">
                                Posts
                            </a>
                            {% endif %}

                            
                            {% if not current_user.is_authenticated %}
                            <a href="{{ url_for('auth.login') }}" class="navbar-item">
                                Login
                            </a>

                            <a href="{{ url_for('auth.signup') }}" class="navbar-item">
                                Sign Up
                            </a>
                            {% endif %}

                            
                            {% if current_user.is_authenticated %}
                            <a href="{{ url_for('auth.logout') }}" class="navbar-item">
                                Logout
                            </a>
                            {% endif %}

                        </div>
                    </div>
                </div>
            </nav>
        </div>

        <div class="hero-body">
            <div class="container has-text-centered">
               {% block content %}
               {% endblock %}
            </div>
        </div>
    </section>
</body>

</html>

myapp/templates/index.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome To this Site!
</h1>

{% if current_user.is_authenticated %}
<h2 class="subtitle">
  You are Logged In
</h2>
{% endif %}

{% if not current_user.is_authenticated %}
<h2 class="subtitle">
  You are Not Logged In, Please Login to Enjoy Full Features
</h2>
{% endif %}


{% endblock %}

myapp/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Login</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}
            </div>
        {% endif %}
        {% endwith %}

        <form method="POST" action="/login">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Your Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Your Password">
                </div>
            </div>
            <div class="field">
                <label class="checkbox">
                    <input type="checkbox">
                    Remember me
                </label>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

myapp/templates/posts.html
{% extends "base.html" %}

{% block content %}

{% if current_user.is_authenticated %}
<h1 class="User Posts">
  <strong> Welcome To Posts Page </strong>
</h1>
{% endif %}

{% if not current_user.is_authenticated %}
<h1 class="User Posts">
    <strong> Please Login to View your Posts </strong>
</h1>
{% endif %}


{% if current_user.is_authenticated %}
<table id="data" class="table table-striped", align="center">
    {% if all_posts %}
        <thead>
            <th>
                <strong>Title</strong>
            </th>

            <th>
                <strong>Description</strong>
            </th>
            
            <th>
                <strong>Datetime</strong>
            </th>

            <th>
                <strong>User_ID</strong>
            </th>
        </thead>

    <tbody>

        {% for single_post in all_posts %}
        <tr>
            <td>
                {{single_post.title}}
            </td>

            <td>
                {{single_post.description}}
            </td>

            <td>
                {{single_post.created_at}}
            </td>

            <td>
                {{single_post.user_id}}
            </td>


        </tr>
        {% endfor %}

    </tbody>
    
    {% else %}
        <h2>
            <div>
                No Posts Found
            </div>
        </h2>

    {% endif %}

{% endif %}
</table>



{% endblock %}

myapp/templates/profile.html
{% extends "base.html" %}

{% block content %}
<h1 class="title">
  Welcome, to Your Profile {{username}}!
</h1>
{% endblock %}

myapp/templates/signup.html
{% extends "base.html" %}

{% block content %}
<div class="column is-4 is-offset-4">
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('auth.login') }}">login page</a>.
            </div>
        {% endif %}
        {% endwith %}

        <form method="POST" action="/signup">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="email" name="email" placeholder="Email" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="username" placeholder="User Name" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="password" name="password" placeholder="Password">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="role" placeholder="Role">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="status" placeholder="Status">
                </div>
            </div>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}